App\Entity\Rating:
  properties:
    mark:
      - LessThan: {value: 5, groups: [registration], message: The mark must be less than 5}
      - Type: {type: float, message: The mark must be a Float}
    authorUserMail:
      - Email: {message: The email is not a valid email., groups: [registration]}
